shinyUI(fluidPage(
  titlePanel("Network Family Metrics Visualizer"),
  sidebarLayout(
    sidebarPanel(width=3,
                 fileInput('file1', 'Choose CSV File',
                           multiple = TRUE,
                           accept=c('text/csv', 
                                    'text/comma-separated-values,text/plain', 
                                    '.csv')),
                 tags$hr(),
                 checkboxInput('header', 'Header', TRUE),
                 radioButtons('sep', 'Separator',
                              c(Comma=',',
                                Semicolon=';',
                                Tab='\t'),
                              ','),
                 radioButtons('quote', 'Quote',
                              c(None='',
                                'Double Quote'='"',
                                'Single Quote'="'"),
                              '"')
                 
                 
    ),
    mainPanel(width=9,
              tabsetPanel(
                tabPanel("Degree Centralization",
                         plotOutput("Degree"),               
                         value = 1),
                tabPanel("Betweenness Centralization",
                         plotOutput("Betweenness"),               
                         value = 2),
                tabPanel("Closeness Centralization",
                         plotOutput("Closeness"),               
                         value = 3),
                tabPanel("Eigenvector Centralization",
                         plotOutput("Eigenvector"),               
                         value = 4),
                tabPanel("Global Clustering Coefficient",
                         plotOutput("cluster"),
                         value=5),
                tabPanel("Assortativity",
                         plotOutput("Assortativity"),               
                         value = 6),
                tabPanel("Diameter",
                         plotOutput("diameter"),               
                         value = 7),
                tabPanel("Average Degree",
                         plotOutput("avgdegree"),
                         value=8),
                tabPanel("Modularity",
                         plotOutput("modularity"),
                         value=9),
                tabPanel("Density",
                         plotOutput("density"),
                         value=10),
                tabPanel("Average Separation",
                         plotOutput("avgsep"),
                         value=11),
                tabPanel("Vertices",
                         plotOutput("vc"),
                         value=12),
                tabPanel("Edges",
                         plotOutput("ec"),
                         value=13),
                id="tabs1")
    )
  )))
